### ISSUE TITLE
Plot can't be generated when all elements have same counts

### ISSUE THREAD

**Issue by vmeschke** [arosen93/ptable_trends#6]
I've been trying to generate a plot with certain elements highlighted, but there isn't a count for them. I provided a column of 1's as the counts. No plot appeared when the code finished running, though a browser tab did open. Changing one of the element counts to 2 instead of 1 or 0 instead of 1 did fix this, but not with the desired outcome.

**Comment by arosen93** [comment]
Thanks for reporting this. I will take a look later today and get back to you.

**Comment by arosen93** [comment]
Hi again @vmeschke. I was able to reproduce your issue. This is likely because `ptable_trends` is trying to generate a color bar to show trends in the data, but seeing as all the values are identical, it is incapable of doing so and silently fails. You can see this for yourself in the `color_mapper` variable of `ptable_trends.py` (e.g. Line 130), where it is specifying the `low` and `high` bounds for the color map.

Fortunately, there is a simple workaround for this. If you look at line 158 of `ptable_trends.py`, you will see a list `color_list`. This is used in line 167 in the `type_color` argument to define the color of each element. If you would like to force the color to be the same for select elements, you can simply provide the [hexadecimal color string](https://htmlcolorcodes.com/) for the relevant elements in the list.

For instance, changing `color_list[element_index] = to_hex(color_scale[i])` to `color_list[element_index] = #FF5733` would make all elements red. You can have certain elements colored simply by adjusting the hex color for each relevant entry in the loop.

An alternate route is to use bokeh's own [periodic.py](https://docs.bokeh.org/en/latest/docs/gallery/periodic.html) script. It becomes quite easy to alter colors this way. The `ptable_trends` script I have made is primarily meant for plotting trends, so that's why some tricks are needed if the data is all uniform.
